export interface Rocket {
    id: number;
    url: string;
    name: string;
    description: string;
    family: string;
    full_name: string;
    manufacturer: {
        id: number;
        url: string;
        name: string;
        featured: boolean;
        type: string;
        country_code: string;
        abbrev: string;
        description: string;
        administrator: string;
        founding_year: number;
        launchers: string;
        spacecraft: string;
        launch_library_url: string;
        total_launch_count: number;
        consecutive_successful_launches: number;
        successful_launches: number;
        failed_launches: number;
        pending_launches: number;
        consecutive_successful_landings: number;
        successful_landings: number;
        failed_landings: number;
        attempted_landings: number;
        info_url: string;
        wiki_url: string;
        logo_url: string;
        image_url: string;
        nation_url: string;
    }
    program: [{
        id: number,
        url: string,
        name: string,
        description: string,
        agencies: [{
            id: number,
            url: string,
            name: string,
            type: string
        }]
    }]
    variant: number;
    alias: string;
    min_stage: number;
    max_stage: number;
    length: number;
    diameter: number;
    maiden_flight: string;
    launch_cost: number;
    launch_mass: number;
    leo_capacity: number;
    gto_capacity: number;
    to_thrust: number;
    apogee: number;
    vehicle_range: number;
    image_url: string;
    info_url: string;
    wiki_url: string;
    total_launch_count: number;
    consecutive_successful_launches: number;
    successful_launches: number;
    failed_launches: number;
    pending_launches: number;
}

